config/routes.rb
Rails.application.routes.draw do
  root "dinosaurs#index"

  resources :dinosaurs

  #get "dinosaurs" => "dinosaurs#index"
  #get 'dinosaurs/new' => "dinosaurs#new", as: :new_dinosaur
  #get "dinosaurs/:id" => "dinosaurs#show", as: :dinosaur

  #post "dinosaurs" => "dinosaurs#create"

  #get 'dinosaurs/:id/edit' => 'dinosaurs#edit', as: :edit_dinosaur

  #patch "dinosaurs/:id" => "dinosaurs#update"

  #delete "dinosaurs/:id" => "dinosaurs#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dinosaur.rb
class Dinosaur < ApplicationRecord
    def self.order_by_name
      order(:name)
    end

    def is_baby?
        age < 3
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController
  def index
    @dinosaurs = Dinosaur.all
  end
  def show
    @dinosaurs = Dinosaur.find(params[:id])
  end
  def new
    @dinosaurs = Dinosaur.new
  end
  def create
    # dinosaur_params = params.require(:dinosaur).permit(:name, :age, :image_url)

    @dinosaurs = Dinosaur.new(dinosaur_params)

    if @dinosaurs.save
      redirect_to @dinosaurs
    else
     render 'new'
    end
  end

  def edit
    @dinosaurs = Dinosaur.find(params[:id])
  end

  def update
    @dinosaur = Dinosaur.find(params[:id])

    # dinosaur_params = params.require(:dinosaur).permit(:name, :age, :image_url)

    if @dinosaur.update_attributes(dinosaur_params)
      redirect_to @dinosaurs
    else
      render 'edit'
    end
  end

  def destroy
    @dinosaur = Dinosaur.find(params[:id])

    @dinosaur.destroy

    redirect_to dinosaurs_path
  end

  private

  def dinosaur_params
    params.require(:dinosaur).permit(:name, :age, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/views/dinosaurs/_form.html.erb
<!-- app/views/dinosaurs/_form.html.erb -->

<%= form_for @dinosaurs do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.submit (@dinosaurs.new_record? ? "Create" : "Update") %>

<% end %>

app/views/dinosaurs/edit.html.erb
<!-- app/views/dinosaurs/edit.html.erb -->

<h1>Edit Dinosaur</h1>

<%= render "form" %>

app/views/dinosaurs/index.html.erb
<h1>Dinosaurs</h1>

<% @dinosaurs.each do |dinosaur| %>
    <p><%= link_to dinosaur.name, dinosaur_path(dinosaur.id) %></p>
<% end %>

<hr>

<%= link_to "[New Dinosaur]", new_dinosaur_path %>

app/views/dinosaurs/new.html.erb
<!-- app/views/dinosaurs/new.html.erb -->

<h1>New Dinosaur</h1>

<%= render "form" %>

app/views/dinosaurs/show.html.erb
<h1><%= @dinosaurs.name %></h1>

<p>Age: <%= @dinosaurs.age %></p>
<%= image_tag @dinosaurs.image_url %>

<hr>

<%= link_to "[Edit]", edit_dinosaur_path(@dinosaurs.id) %>
<%= link_to "[Delete]", dinosaur_path(@dinosaur.id), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ValleysOfDinosaurs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= yield %>

  <br><br>
  <hr>

  <%= link_to "[All Dinosaurs]", root_path %>

  </body
</html>